# -*- coding: utf-8 -*-
"""WHATSYOURNAME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Z2xqrVh9TaUYBetGj993yS83tc6j_E8
"""

pip install keyboard
import keyboard

friedFishCost = 100
friedFishCount = 0
hunger = 100
balance = -9000

while True:
  if keyboard.is_pressed('q'):
    balance += 20

  if keyboard.is_pressed('w'):
    if not balance < friedFishCost:
      balance -= friedFishCost
      friedFishCount += 1

  if keyboard.is_pressed('e'):
    if friedFishCount > 0:
      friedFishCount -= 1
      hunger -= 1

name = input("What's your name? ")
age = input("What's your age? ")

print(name + ": " + age + " years old")

if input("spell truck ") == "truck":
  if input("now spell pneumonoultramicroscopicsilicovolcanoconiosis ") == "pneumonoultramicroscopicsilicovolcanoconiosis":
    print("good job you win")
  else:
    print("NOOB!!!!!!")
else:
  print("NOOB!!!!!!")